line_length: 300
disabled_rules:
- function_body_length
- type_body_length
- file_length
- redundant_string_enum_value
- trailing_whitespace
- redundant_optional_initialization
- force_try
- closure_parameter_position
- unused_optional_binding
- identifier_name
- force_cast
- unused_closure_parameter
- type_name
- cyclomatic_complexity
- nesting
- opening_brace
- weak_delegate
- syntactic_sugar
- empty_enum_arguments
- unused_setter_value
